// packages/react/src/components/Badge.tsx
import React from 'react';
import '@fs-ds/web-components/badge';
import type { BadgeVariant, BadgeSize } from '@fs-ds/web-components';

export interface BadgeProps extends React.HTMLAttributes<HTMLElement> {
  variant?: BadgeVariant;
  size?: BadgeSize;
}

/**
 * FS Badge — React wrapper for `<fs-badge>`.
 *
 * @example
 * <Badge variant="success">Active</Badge>
 */
export const Badge = React.forwardRef<HTMLElement, BadgeProps>(
  ({ children, variant = 'default', size = 'md', ...props }, ref) => {
    return (
      // @ts-expect-error — custom element not in React's intrinsics
      <fs-badge ref={ref} variant={variant} size={size} {...props}>
        {children}
        {/* @ts-expect-error */}
      </fs-badge>
    );
  }
);

Badge.displayName = 'Badge';

// packages/angular/src/components/badge/badge.component.ts
import {
  Component,
  Input,
  ViewEncapsulation,
  ChangeDetectionStrategy,
  CUSTOM_ELEMENTS_SCHEMA,
} from '@angular/core';
import '@fs-ds/web-components/badge';
import type { BadgeVariant, BadgeSize } from '@fs-ds/web-components';

/**
 * FsBadgeComponent — Angular wrapper for `<fs-badge>`.
 *
 * @example
 * <fs-badge-component variant="success">Active</fs-badge-component>
 */
@Component({
  selector: 'fs-badge-component',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <fs-badge [attr.variant]="variant" [attr.size]="size">
      <ng-content />
    </fs-badge>
  `,
  encapsulation: ViewEncapsulation.None,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class FsBadgeComponent {
  @Input() variant: BadgeVariant = 'default';
  @Input() size: BadgeSize = 'md';
}
