// packages/angular/src/components/button/button.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
  ViewEncapsulation,
  ChangeDetectionStrategy,
  CUSTOM_ELEMENTS_SCHEMA,
  OnInit,
} from '@angular/core';
import '@fs-ds/web-components/button';
import type { ButtonVariant, ButtonSize } from '@fs-ds/web-components';

/**
 * FsButtonComponent — Angular wrapper for `<fs-button>`.
 *
 * @example
 * <fs-button-component variant="primary" size="md" (buttonClick)="onSave()">
 *   Save
 * </fs-button-component>
 */
@Component({
  selector: 'fs-button-component',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <fs-button
      [attr.variant]="variant"
      [attr.size]="size"
      [attr.disabled]="disabled || null"
      [attr.loading]="loading || null"
      [attr.type]="type"
      (click)="handleClick($event)"
    >
      <ng-content select="[slot=icon-left]" />
      <ng-content />
      <ng-content select="[slot=icon-right]" />
    </fs-button>
  `,
  encapsulation: ViewEncapsulation.None,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class FsButtonComponent implements OnInit {
  @Input() variant: ButtonVariant = 'primary';
  @Input() size: ButtonSize = 'md';
  @Input() disabled = false;
  @Input() loading = false;
  @Input() type: 'button' | 'submit' | 'reset' = 'button';

  @Output() buttonClick = new EventEmitter<MouseEvent>();

  ngOnInit() {
    // Ensure custom element is registered
  }

  handleClick(event: MouseEvent) {
    if (!this.disabled && !this.loading) {
      this.buttonClick.emit(event);
    }
  }
}

// packages/react/src/components/Button.tsx
import React from 'react';
// Side-effect import: registers the custom element
import '@fs-ds/web-components/button';
import type { ButtonVariant, ButtonSize } from '@fs-ds/web-components';

export interface ButtonProps extends React.HTMLAttributes<HTMLElement> {
  variant?: ButtonVariant;
  size?: ButtonSize;
  disabled?: boolean;
  loading?: boolean;
  type?: 'button' | 'submit' | 'reset';
  /** Convenience: icon rendered before label */
  iconLeft?: React.ReactNode;
  /** Convenience: icon rendered after label */
  iconRight?: React.ReactNode;
}

/**
 * FS Button — React wrapper for `<fs-button>`.
 *
 * @example
 * <Button variant="primary" size="md" onClick={() => {}}>Save</Button>
 */
export const Button = React.forwardRef<HTMLElement, ButtonProps>(
  ({ children, variant = 'primary', size = 'md', iconLeft, iconRight, ...props }, ref) => {
    return (
      // @ts-expect-error — custom element not in React's intrinsics
      <fs-button ref={ref} variant={variant} size={size} {...props}>
        {iconLeft && <span slot="icon-left">{iconLeft}</span>}
        {children}
        {iconRight && <span slot="icon-right">{iconRight}</span>}
        {/* @ts-expect-error */}
      </fs-button>
    );
  }
);

Button.displayName = 'Button';
