// apps/demo-angular/src/app/app.component.ts
import { Component, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { FsDsModule } from '@fs-ds/angular';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [FormsModule, FsDsModule],
  template: `
    <div class="container">
      <h1>FS Design System</h1>
      <p class="subtitle">Angular consumer demo</p>

      <div class="badges">
        <fs-badge-component variant="success">Angular 17</fs-badge-component>
        <fs-badge-component variant="info">Standalone</fs-badge-component>
        <fs-badge-component variant="default">&#64;fs-ds/angular</fs-badge-component>
      </div>

      @if (submitted()) {
        <div class="success-card">
          <fs-badge-component variant="success">Submitted!</fs-badge-component>
          <p>Email: <strong>{{ email }}</strong></p>
          <fs-button-component variant="ghost" (buttonClick)="reset()">Reset</fs-button-component>
        </div>
      } @else {
        <form (ngSubmit)="submit()" class="form">
          <fs-input-component
            label="Email address"
            type="email"
            placeholder="you@example.com"
            [(ngModel)]="email"
            name="email"
            [required]="true"
          ></fs-input-component>

          <div class="actions">
            <fs-button-component type="submit" variant="primary" [loading]="loading()">
              {{ loading() ? 'Submitting…' : 'Submit' }}
            </fs-button-component>
            <fs-button-component variant="secondary" type="button" (buttonClick)="email = ''">
              Clear
            </fs-button-component>
          </div>
        </form>
      }

      <hr />

      <section>
        <h2>All button variants</h2>
        <div class="buttons">
          <fs-button-component variant="primary">Primary</fs-button-component>
          <fs-button-component variant="secondary">Secondary</fs-button-component>
          <fs-button-component variant="ghost">Ghost</fs-button-component>
          <fs-button-component variant="danger">Danger</fs-button-component>
          <fs-button-component variant="primary" [disabled]="true">Disabled</fs-button-component>
        </div>
      </section>
    </div>
  `,
  styles: [`
    .container { max-width: 480px; margin: 48px auto; padding: 0 16px; }
    h1 { font-size: var(--fs-text-2xl); font-weight: var(--fs-font-weight-bold); margin: 0 0 8px; }
    .subtitle { color: var(--fs-color-neutral-500); margin: 0 0 24px; }
    .badges { display: flex; gap: 8px; margin-bottom: 24px; }
    .form { display: flex; flex-direction: column; gap: 16px; }
    .actions { display: flex; gap: 8px; }
    .success-card { padding: 16px; background: var(--fs-color-success-light); border-radius: var(--fs-radius-lg); }
    .success-card p { margin: 8px 0; color: var(--fs-color-success-dark); }
    hr { margin: 40px 0; border-color: var(--fs-color-neutral-200); }
    h2 { font-size: var(--fs-text-lg); font-weight: var(--fs-font-weight-semibold); margin: 0 0 16px; }
    .buttons { display: flex; gap: 8px; flex-wrap: wrap; }
  `],
})
export class AppComponent {
  email = '';
  submitted = signal(false);
  loading = signal(false);

  async submit() {
    this.loading.set(true);
    await new Promise(r => setTimeout(r, 1200));
    this.loading.set(false);
    this.submitted.set(true);
  }

  reset() {
    this.email = '';
    this.submitted.set(false);
  }
}

// apps/demo-react/src/App.tsx
import { useState } from 'react';
import { Button, Input, Badge } from '@fs-ds/react';

export default function App() {
  const [email, setEmail] = useState('');
  const [submitted, setSubmitted] = useState(false);
  const [loading, setLoading] = useState(false);

  const handleSubmit = async () => {
    setLoading(true);
    await new Promise(r => setTimeout(r, 1200));
    setLoading(false);
    setSubmitted(true);
  };

  return (
    <div style={{ maxWidth: 480, margin: '48px auto', padding: '0 16px', fontFamily: 'var(--fs-font-sans)' }}>
      <h1 style={{ fontSize: 'var(--fs-text-2xl)', fontWeight: 'var(--fs-font-weight-bold)', marginBottom: 8 }}>
        FS Design System
      </h1>
      <p style={{ color: 'var(--fs-color-neutral-500)', marginBottom: 32 }}>
        React consumer demo
      </p>

      <div style={{ display: 'flex', gap: 8, marginBottom: 24 }}>
        <Badge variant="success">React 18</Badge>
        <Badge variant="info">Vite</Badge>
        <Badge variant="default">@fs-ds/react</Badge>
      </div>

      {submitted ? (
        <div style={{ padding: 16, background: 'var(--fs-color-success-light)', borderRadius: 'var(--fs-radius-lg)' }}>
          <Badge variant="success">Submitted!</Badge>
          <p style={{ margin: '8px 0 0', color: 'var(--fs-color-success-dark)' }}>
            Email: <strong>{email}</strong>
          </p>
          <Button variant="ghost" style={{ marginTop: 8 }} onClick={() => { setSubmitted(false); setEmail(''); }}>
            Reset
          </Button>
        </div>
      ) : (
        <form onSubmit={e => { e.preventDefault(); handleSubmit(); }} style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
          <Input
            label="Email address"
            type="email"
            placeholder="you@example.com"
            value={email}
            onChange={setEmail}
            required
          />
          <div style={{ display: 'flex', gap: 8 }}>
            <Button type="submit" variant="primary" loading={loading}>
              {loading ? 'Submitting…' : 'Submit'}
            </Button>
            <Button variant="secondary" type="button" onClick={() => setEmail('')}>
              Clear
            </Button>
          </div>
        </form>
      )}

      <hr style={{ margin: '40px 0', borderColor: 'var(--fs-color-neutral-200)' }} />

      <section>
        <h2 style={{ fontSize: 'var(--fs-text-lg)', fontWeight: 'var(--fs-font-weight-semibold)', marginBottom: 16 }}>
          All button variants
        </h2>
        <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
          <Button variant="primary">Primary</Button>
          <Button variant="secondary">Secondary</Button>
          <Button variant="ghost">Ghost</Button>
          <Button variant="danger">Danger</Button>
          <Button variant="primary" disabled>Disabled</Button>
        </div>
      </section>
    </div>
  );
}
